server {
  listen 80;
  listen [::]:80;
  server_name kuygas.my.id;
  root /home/padsu/www/kuygas.my.id;

  location ~ /.well-known {
    allow all;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}