server {
  listen 80;
  listen [::]:80;
  server_name kuygas.my.id;

  location ~ /.well-known {
    allow all;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;
  server_name kuygas.my.id;

  ssl_certificate /etc/letsencrypt/live/kuygas.my.id/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/kuygas.my.id/privkey.pem;

  access_log /home/padsu/logs/nginx/kuygas.access.log main;
  error_log /home/padsu/logs/nginx/kuygas.error.log;

  client_max_body_size 10m;

  location / {
    proxy_pass http://127.0.0.1:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
  }

  location /_next/static {
    alias /home/padsu/scripts/smm-panel/.next/static;
    expires 365d;
    access_log off;
  }
}